version: '3.9'

services:
  backend:
    build: ./
    container_name: pedemusica_api
    ports:
      - '3100:3100'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge