export enum PERMISSION_TYPE {
    //Functions
    CAN_MANAGE_INIT_SYSTEM = 'CAN_MANAGE_INIT_SYSTEM',
    CAN_MANAGE_REPORT = 'CAN_MANAGE_REPORT',
    CAN_MANAGE_FINANCE = 'CAN_MANAGE_FINANCE',
    CAN_MANAGE_TABLES = 'CAN_MANAGE_TABLES',
    CAN_MANAGE_ORDERS = 'CAN_MANAGE_ORDERS',

    //Registers
    CAN_MANAGE_USERS = 'CAN_MANAGE_USERS',
    CAN_MANAGE_MENU = 'CAN_MANAGE_MENU',
    CAN_MANAGE_SECTORS = 'CAN_MANAGE_SECTORS',
    CAN_MANAGE_SETTINGS = 'CAN_MANAGE_SETTINGS',
}
